version: "3.8"

services:
  ping-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./docs/logs:/app/logs  # opcional si querés guardar logs en archivo
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    restart: always
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always
    networks:
      - monitor-net

  telegram-webhook:
    build: ./src/telegram-webhook
    ports:
      - "5000:5000"
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
    restart: always
    networks:
      - monitor-net

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    networks:
      - monitor-net

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail.yaml:/etc/promtail/promtail.yaml
      - ./docs/logs:/var/log/ping-monitor
    command: -config.file=/etc/promtail/promtail.yaml
    restart: always
    networks:
      - monitor-net

volumes:
  grafana-storage:

networks:
  monitor-net:
