apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  config.yml: |
    global: {}

    route:
      receiver: telegram-webhook

    receivers:
      - name: telegram-webhook
        webhook_configs:
          - url: 'http://telegram-webhook.default.svc.cluster.local:5000/alert'
            send_resolved: true
