global:
  resolve_timeout: 5m

route:
  group_by: [namespace]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: "null"
  routes:
    - matchers:
        - job = "network-monitor-service"
      receiver: telegram-webhook

receivers:
  - name: telegram-webhook
    webhook_configs:
      - url: 'http://telegram-webhook.default.svc.cluster.local:5000/alert'
        send_resolved: true

  - name: "null"

inhibit_rules:
  - equal: [namespace, alertname]
    source_matchers: [severity = critical]
    target_matchers: [severity =~ warning|info]
  - equal: [namespace, alertname]
    source_matchers: [severity = warning]
    target_matchers: [severity = info]
  - equal: [namespace]
    source_matchers: [alertname = InfoInhibitor]
    target_matchers: [severity = info]
  - target_matchers: [alertname = InfoInhibitor]

templates:
  - /etc/alertmanager/config/*.tmpl
