apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  config.yml: |
    global:
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'monitoring@duckdns.org'
      smtp_auth_username: 'steven777cr@gmail.com'
      smtp_auth_password: 'iodungmjwvmzrdqz'
      smtp_require_tls: true

    route:
      receiver: email-alerts

    receivers:
      - name: email-alerts
        email_configs:
          - to: 'steven777psn@gmail.com'
            send_resolved: true
