apiVersion: v1
kind: Service
metadata:
  name: network-monitor-service
  namespace: monitoring
  labels:
    app: monitor  # ← alineado con el Deployment
    grafana_dashboard: "true"  #  auto-discovery en grafana
spec:
  selector:
    app: monitor
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  type: ClusterIP
