apiVersion: v1
kind: Service
metadata:
  name: network-monitor-service
  namespace: monitoring
  labels:
    app: monitor
spec:
  selector:
    app: monitor
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
  type: ClusterIP
