apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-endpoint-reader-binding
  namespace: monitoring
subjects:
- kind: ServiceAccount
  name: kube-prometheus-stack-prometheus
  namespace: monitoring
roleRef:
  kind: Role
  name: prometheus-endpoint-reader
  apiGroup: rbac.authorization.k8s.io
