name: Deploy Monitoring Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: $HOME/.kube/config

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Test kubectl connection
        run: kubectl cluster-info

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible kubectl

      - name: Run Ansible playbook
        run: ansible-playbook ansible/playbooks/deploy-monitoring.yml
